name: Keep Development Up-to-Date with Main

on:
  push:
    branches:
      - main  # Trigger when new commits are pushed to main
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight (UTC)

jobs:
  update-development:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure Git
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    # Fetch all branches
    - name: Fetch all branches
      run: git fetch --all

    # Merge main into development
    - name: Merge main into development
      run: |
        git checkout development
        git rebase main 
        git rebase --continue

    # Push the changes
    - name: Push changes to development
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin development --force || echo "No updates to push."
